services:
  fastapi_app:
    build: .
    container_name: fastapi_project
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    image: nux-caddy:local
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - app_network
    depends_on:
      - fastapi_app

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  app_network: