services:
  fastapi_app:
    build: .
    container_name: fastapi_project
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"   # слушаем на всех интерфейсах, порт 8000
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db           # гарантируем, что база запустится первой

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"   # доступ к БД снаружи (опционально, можно убрать)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: